# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-14 18:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import pjtk2.models
import taggit.managers


class Migration(migrations.Migration):

    replaces = [
        ("pjtk2", "0001_initial"),
        ("pjtk2", "0002_auto_20171117_0847"),
        ("pjtk2", "0003_auto_20171117_0852"),
        ("pjtk2", "0004_auto_20171117_0854"),
        ("pjtk2", "0005_auto_20171129_1603"),
        ("pjtk2", "0006_auto_20171205_1127"),
        ("pjtk2", "0007_auto_20171205_1202"),
        ("pjtk2", "0008_auto_20171205_1203"),
        ("pjtk2", "0009_auto_20171205_1203"),
        ("pjtk2", "0010_auto_20180629_1024"),
        ("pjtk2", "0011_auto_20180629_1031"),
        ("pjtk2", "0012_auto_20180629_1050"),
        ("pjtk2", "0013_auto_20180629_1105"),
        ("pjtk2", "0014_auto_20180705_1704"),
        ("pjtk2", "0015_auto_20180710_1145"),
        ("pjtk2", "0016_auto_20180711_1143"),
        ("pjtk2", "0017_auto_20180712_0928"),
        ("pjtk2", "0018_auto_20180712_1202"),
        ("pjtk2", "0019_auto_20180712_1411"),
        ("pjtk2", "0020_auto_20181009_1133"),
        ("pjtk2", "0021_auto_20181011_0934"),
        ("pjtk2", "0022_auto_20181011_1155"),
        ("pjtk2", "0023_auto_20181012_0915"),
        ("pjtk2", "0024_auto_20190113_1724"),
        ("pjtk2", "0025_auto_20190113_1818"),
        ("pjtk2", "0026_auto_20190113_1818"),
        ("pjtk2", "0027_auto_20190113_1819"),
    ]

    initial = True

    dependencies = [
        ("taggit", "0002_auto_20150616_2121"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssociatedFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(
                        max_length=200,
                        upload_to=pjtk2.models.AssociatedFile.get_associated_file_upload_path,
                    ),
                ),
                ("current", models.BooleanField(default=True)),
                ("uploaded_on", models.DateTimeField(auto_now_add=True)),
                ("hash", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-date"]},
        ),
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("master_database", models.CharField(max_length=250)),
                ("path", models.CharField(max_length=250)),
            ],
            options={"verbose_name": "Master Database"},
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=60)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("employee", "Employee"),
                            ("manager", "Manager"),
                            ("dba", "DBA"),
                        ],
                        default="Employee",
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Family",
            fields=[("id", models.AutoField(primary_key=True, serialize=False))],
            options={"verbose_name_plural": "Families"},
        ),
        migrations.CreateModel(
            name="Lake",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lake", models.CharField(max_length=50)),
            ],
            options={"verbose_name": "Lake"},
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msgtxt", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("actionrequired", "Action Required"),
                            ("info", "Info"),
                        ],
                        default="info",
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Messages2Users",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("read", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pjtk2.Message"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Messages2Users"},
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50, unique=True)),
                ("label_abbrev", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Core", "core"),
                            ("Custom", "custom"),
                            ("Suggested", "suggested"),
                        ],
                        default="Custom",
                        max_length=30,
                    ),
                ),
                ("report", models.BooleanField(default=False)),
                ("shared", models.BooleanField(default=False)),
                ("protected", models.BooleanField(default=False)),
                ("order", models.FloatField(default=99)),
            ],
            options={
                "verbose_name_plural": "Milestones List",
                "verbose_name": "Milestone List",
                "ordering": ["-report", "order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("cancelled", models.BooleanField(default=False)),
                (
                    "year",
                    models.CharField(
                        blank=True, editable=False, max_length=4, verbose_name="Year"
                    ),
                ),
                ("prj_date0", models.DateField(verbose_name="Start Date")),
                ("prj_date1", models.DateField(verbose_name="End Date")),
                (
                    "prj_cd",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="Project Code"
                    ),
                ),
                (
                    "prj_nm",
                    models.CharField(max_length=60, verbose_name="Project Name"),
                ),
                ("comment", models.TextField(help_text="General project description.")),
                (
                    "comment_html",
                    models.TextField(
                        blank=True, help_text="General project description.", null=True
                    ),
                ),
                (
                    "risk",
                    models.TextField(
                        blank=True,
                        help_text="Potential risks associated with not running project.",
                        null=True,
                        verbose_name="Risk",
                    ),
                ),
                (
                    "risk_html",
                    models.TextField(
                        blank=True,
                        help_text="Potential risks associated with not running project.",
                        null=True,
                        verbose_name="Risk",
                    ),
                ),
                (
                    "funding",
                    models.CharField(
                        choices=[("spa", "SPA"), ("other", "other"), ("coa", "COA")],
                        default="spa",
                        max_length=30,
                        verbose_name="Funding Source",
                    ),
                ),
                (
                    "odoe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        null=True,
                        verbose_name="ODOE",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        null=True,
                        verbose_name="Salary",
                    ),
                ),
                ("slug", models.SlugField(blank=True, editable=False)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CancelledBy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dba",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ProjectDBA",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field_ldr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="FieldLead",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lake",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pjtk2.Lake",
                    ),
                ),
                (
                    "master_database",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pjtk2.Database",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ProjectOwner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prj_ldr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ProjectLead",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Project List", "ordering": ["-prj_date1"]},
        ),
        migrations.CreateModel(
            name="ProjectMilestones",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("completed", models.DateTimeField(blank=True, null=True)),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pjtk2.Milestone",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pjtk2.Project"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Project Milestones"},
        ),
        migrations.CreateModel(
            name="ProjectSisters",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pjtk2.Family"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pjtk2.Project"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project Sisters",
                "ordering": ["family", "project"],
            },
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_type", models.CharField(max_length=150)),
                ("field_component", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "Project Type"},
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current", models.BooleanField(default=True)),
                (
                    "report_path",
                    models.FileField(max_length=200, upload_to="milestone_reports/"),
                ),
                ("uploaded_on", models.DateTimeField(auto_now_add=True)),
                ("report_hash", models.CharField(max_length=300)),
                ("projectreport", models.ManyToManyField(to="pjtk2.ProjectMilestones")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SamplePoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sam", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Represented as (longitude, latitude)", srid=4326
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pjtk2.Project"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pjtk2.ProjectType",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="distribution_list",
            field=models.ManyToManyField(
                through="pjtk2.Messages2Users", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="project_milestone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pjtk2.ProjectMilestones",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="lake",
            field=models.ManyToManyField(to="pjtk2.Lake"),
        ),
        migrations.AddField(
            model_name="employee",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pjtk2.Employee",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pjtk2.Project"
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_bookmark",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="associatedfile",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pjtk2.Project"
            ),
        ),
        migrations.AddField(
            model_name="associatedfile",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectmilestones", unique_together=set([("project", "milestone")])
        ),
        migrations.AlterUniqueTogether(
            name="messages2users", unique_together=set([("user", "message")])
        ),
        migrations.CreateModel(
            name="ProjectPolygon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("dba", "DBA"),
                    ("employee", "Employee"),
                    ("manager", "Manager"),
                ],
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="level",
            field=models.CharField(
                choices=[("info", "Info"), ("actionrequired", "Action Required")],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding",
            field=models.CharField(
                choices=[("spa", "SPA"), ("coa", "COA"), ("other", "other")],
                default="spa",
                max_length=30,
                verbose_name="Funding Source",
            ),
        ),
        migrations.AddField(
            model_name="projectpolygon",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to="pjtk2.Project",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                    ("dba", "DBA"),
                ],
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Custom", "custom"),
                    ("Core", "core"),
                    ("Suggested", "suggested"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding",
            field=models.CharField(
                choices=[("other", "other"), ("coa", "COA"), ("spa", "SPA")],
                default="spa",
                max_length=30,
                verbose_name="Funding Source",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("manager", "Manager"),
                    ("dba", "DBA"),
                ],
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="level",
            field=models.CharField(
                choices=[("actionrequired", "Action Required"), ("info", "Info")],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Custom", "custom"),
                    ("Suggested", "suggested"),
                    ("Core", "core"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding",
            field=models.CharField(
                choices=[("coa", "COA"), ("spa", "SPA"), ("other", "other")],
                default="spa",
                max_length=30,
                verbose_name="Funding Source",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("dba", "DBA"),
                    ("employee", "Employee"),
                ],
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Custom", "custom"),
                    ("Core", "core"),
                    ("Suggested", "suggested"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding",
            field=models.CharField(
                choices=[("spa", "SPA"), ("other", "other"), ("coa", "COA")],
                default="spa",
                max_length=30,
                verbose_name="Funding Source",
            ),
        ),
        migrations.AlterField(
            model_name="projectpolygon",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="convex_hull",
                to="pjtk2.Project",
            ),
        ),
        migrations.AddIndex(
            model_name="samplepoint",
            index=models.Index(
                fields=["project", "geom"], name="pjtk2_sampl_project_9b5b67_idx"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="abstract",
            field=models.TextField(
                default="Abstract", help_text="Project Abstract (public)."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="abstract_html",
            field=models.TextField(
                blank=True, help_text="Project Abstract (public).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("dba", "DBA"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                ],
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Suggested", "suggested"),
                    ("Custom", "custom"),
                    ("Core", "core"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comments or Remarks (internal)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="comment_html",
            field=models.TextField(
                blank=True, help_text="Comments or Remarks (internal)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding",
            field=models.CharField(
                choices=[("coa", "COA"), ("spa", "SPA"), ("other", "other")],
                default="spa",
                max_length=30,
                verbose_name="Funding Source",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("dba", "DBA"),
                    ("employee", "Employee"),
                    ("manager", "Manager"),
                ],
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="level",
            field=models.CharField(
                choices=[("info", "Info"), ("actionrequired", "Action Required")],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Custom", "custom"),
                    ("Suggested", "suggested"),
                    ("Core", "core"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding",
            field=models.CharField(
                choices=[("coa", "COA"), ("other", "other"), ("spa", "SPA")],
                default="spa",
                max_length=30,
                verbose_name="Funding Source",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("dba", "DBA"),
                    ("manager", "Manager"),
                ],
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Core", "core"),
                    ("Custom", "custom"),
                    ("Suggested", "suggested"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding",
            field=models.CharField(
                choices=[("coa", "COA"), ("spa", "SPA"), ("other", "other")],
                default="spa",
                max_length=30,
                verbose_name="Funding Source",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("dba", "DBA"),
                    ("employee", "Employee"),
                    ("manager", "Manager"),
                ],
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="level",
            field=models.CharField(
                choices=[("actionrequired", "Action Required"), ("info", "Info")],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Core", "core"),
                    ("Suggested", "suggested"),
                    ("Custom", "custom"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding",
            field=models.CharField(
                choices=[("spa", "SPA"), ("other", "other"), ("coa", "COA")],
                default="spa",
                max_length=30,
                verbose_name="Funding Source",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("dba", "DBA"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                ],
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Core", "core"),
                    ("Custom", "custom"),
                    ("Suggested", "suggested"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="prj_date0",
            field=models.DateField(db_index=True, verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="prj_date1",
            field=models.DateField(db_index=True, verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="year",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=4,
                verbose_name="Year",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("dba", "DBA"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                ],
                db_index=True,
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="messages2users",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="messages2users",
            name="read",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Suggested", "suggested"),
                    ("Custom", "custom"),
                    ("Core", "core"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding",
            field=models.CharField(
                choices=[("other", "other"), ("coa", "COA"), ("spa", "SPA")],
                default="spa",
                max_length=30,
                verbose_name="Funding Source",
            ),
        ),
        migrations.AlterField(
            model_name="projectmilestones",
            name="completed",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectmilestones",
            name="required",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("dba", "DBA"),
                    ("employee", "Employee"),
                ],
                db_index=True,
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="level",
            field=models.CharField(
                choices=[("info", "Info"), ("actionrequired", "Action Required")],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Core", "core"),
                    ("Custom", "custom"),
                    ("Suggested", "suggested"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding",
            field=models.CharField(
                choices=[("coa", "COA"), ("other", "other"), ("spa", "SPA")],
                default="spa",
                max_length=30,
                verbose_name="Funding Source",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("dba", "DBA"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                ],
                db_index=True,
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="level",
            field=models.CharField(
                choices=[("actionrequired", "Action Required"), ("info", "Info")],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Suggested", "suggested"),
                    ("Custom", "custom"),
                    ("Core", "core"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding",
            field=models.CharField(
                choices=[("spa", "SPA"), ("other", "other"), ("coa", "COA")],
                default="spa",
                max_length=30,
                verbose_name="Funding Source",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="signoff_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="SignOffBy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("dba", "DBA"),
                    ("manager", "Manager"),
                ],
                db_index=True,
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Core", "core"),
                    ("Custom", "custom"),
                    ("Suggested", "suggested"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding",
            field=models.CharField(
                choices=[("coa", "COA"), ("other", "other"), ("spa", "SPA")],
                default="spa",
                max_length=30,
                verbose_name="Funding Source",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_team",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                    ("dba", "DBA"),
                ],
                db_index=True,
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding",
            field=models.CharField(
                choices=[("coa", "COA"), ("spa", "SPA"), ("other", "other")],
                default="spa",
                max_length=30,
                verbose_name="Funding Source",
            ),
        ),
        migrations.CreateModel(
            name="FundingSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbrev", models.CharField(max_length=25, unique=True)),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={"verbose_name": "Funding Source"},
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("manager", "Manager"),
                    ("dba", "DBA"),
                ],
                db_index=True,
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Suggested", "suggested"),
                    ("Core", "core"),
                    ("Custom", "custom"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ProjectFunding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "odoe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        null=True,
                        verbose_name="ODOE",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        null=True,
                        verbose_name="Salary",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_sources",
                        to="pjtk2.Project",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_allocations",
                        to="pjtk2.FundingSource",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("dba", "DBA"),
                    ("employee", "Employee"),
                ],
                db_index=True,
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Core", "core"),
                    ("Custom", "custom"),
                    ("Suggested", "suggested"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.RemoveField(model_name="project", name="funding"),
        migrations.AlterUniqueTogether(
            name="projectfunding", unique_together=set([("project", "source")])
        ),
        migrations.RemoveField(model_name="project", name="odoe"),
        migrations.RemoveField(model_name="project", name="salary"),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("dba", "DBA"),
                    ("manager", "Manager"),
                ],
                db_index=True,
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="level",
            field=models.CharField(
                choices=[("info", "Info"), ("actionrequired", "Action Required")],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Suggested", "suggested"),
                    ("Custom", "custom"),
                    ("Core", "core"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="level",
            field=models.CharField(
                choices=[("actionrequired", "Action Required"), ("info", "Info")],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Custom", "custom"),
                    ("Suggested", "suggested"),
                    ("Core", "core"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        verbose_name="the order that the images are presented",
                    ),
                ),
                (
                    "image_path",
                    models.ImageField(
                        upload_to=pjtk2.models.ProjectImage.get_image_path
                    ),
                ),
                (
                    "caption",
                    models.CharField(max_length=1000, verbose_name="figure caption"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="pjtk2.Project",
                    ),
                ),
                (
                    "report",
                    models.BooleanField(
                        default=True,
                        verbose_name="should this image be included in the annual report too?",
                    ),
                ),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                    ("dba", "DBA"),
                ],
                db_index=True,
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="level",
            field=models.CharField(
                choices=[("info", "Info"), ("actionrequired", "Action Required")],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Custom", "custom"),
                    ("Core", "core"),
                    ("Suggested", "suggested"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("dba", "DBA"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                ],
                db_index=True,
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("dba", "DBA"),
                    ("manager", "Manager"),
                ],
                db_index=True,
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Core", "core"),
                    ("Suggested", "suggested"),
                    ("Custom", "custom"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("dba", "DBA"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                ],
                db_index=True,
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="level",
            field=models.CharField(
                choices=[("actionrequired", "Action Required"), ("info", "Info")],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Custom", "custom"),
                    ("Core", "core"),
                    ("Suggested", "suggested"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Custom", "custom"),
                    ("Suggested", "suggested"),
                    ("Core", "core"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("dba", "DBA"),
                    ("employee", "Employee"),
                ],
                db_index=True,
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="level",
            field=models.CharField(
                choices=[("info", "Info"), ("actionrequired", "Action Required")],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Core", "core"),
                    ("Suggested", "suggested"),
                    ("Custom", "custom"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("dba", "DBA"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                ],
                db_index=True,
                default="Employee",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="level",
            field=models.CharField(
                choices=[("actionrequired", "Action Required"), ("info", "Info")],
                default="info",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="category",
            field=models.CharField(
                choices=[
                    ("Custom", "custom"),
                    ("Core", "core"),
                    ("Suggested", "suggested"),
                ],
                default="Custom",
                max_length=30,
            ),
        ),
    ]
