# Generated by Django 2.2.11 on 2020-06-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjtk2', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER project_update_trigger
            BEFORE INSERT OR UPDATE OF abstract, comment, prj_nm, content_search
            ON pjtk2_project
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              content_search, 'pg_catalog.english', abstract, comment, prj_nm);

            UPDATE pjtk2_project SET content_search = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS project_update_trigger
            ON pjtk2_project;
            """,
        )
    ]
