# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjtk2', '0002_auto_20171117_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee'), ('dba', 'DBA')], default='Employee', max_length=30),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('Custom', 'custom'), ('Core', 'core'), ('Suggested', 'suggested')], default='Custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.CharField(choices=[('other', 'other'), ('coa', 'COA'), ('spa', 'SPA')], default='spa', max_length=30, verbose_name='Funding Source'),
        ),
    ]
