# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjtk2', '0004_auto_20171117_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('dba', 'DBA'), ('employee', 'Employee')], default='Employee', max_length=30),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('Custom', 'custom'), ('Core', 'core'), ('Suggested', 'suggested')], default='Custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.CharField(choices=[('spa', 'SPA'), ('other', 'other'), ('coa', 'COA')], default='spa', max_length=30, verbose_name='Funding Source'),
        ),
        migrations.AlterField(
            model_name='projectpolygon',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convex_hull', to='pjtk2.Project'),
        ),
        migrations.AddIndex(
            model_name='samplepoint',
            index=models.Index(fields=['project', 'geom'], name='pjtk2_sampl_project_9b5b67_idx'),
        ),
    ]
