# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjtk2', '0008_auto_20171205_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('dba', 'DBA'), ('employee', 'Employee'), ('manager', 'Manager')], default='Employee', max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='level',
            field=models.CharField(choices=[('actionrequired', 'Action Required'), ('info', 'Info')], default='info', max_length=30),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('Core', 'core'), ('Suggested', 'suggested'), ('Custom', 'custom')], default='Custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.CharField(choices=[('spa', 'SPA'), ('other', 'other'), ('coa', 'COA')], default='spa', max_length=30, verbose_name='Funding Source'),
        ),
    ]
