# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-05 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pjtk2', '0013_auto_20180629_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='signoff_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SignOffBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('dba', 'DBA'), ('manager', 'Manager')], db_index=True, default='Employee', max_length=30),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('Core', 'core'), ('Custom', 'custom'), ('Suggested', 'suggested')], default='Custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.CharField(choices=[('coa', 'COA'), ('other', 'other'), ('spa', 'SPA')], default='spa', max_length=30, verbose_name='Funding Source'),
        ),
    ]
