# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-10 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pjtk2', '0014_auto_20180705_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_team',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee'), ('dba', 'DBA')], db_index=True, default='Employee', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.CharField(choices=[('coa', 'COA'), ('spa', 'SPA'), ('other', 'other')], default='spa', max_length=30, verbose_name='Funding Source'),
        ),
    ]
