# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-12 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjtk2', '0017_auto_20180712_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('dba', 'DBA'), ('employee', 'Employee')], db_index=True, default='Employee', max_length=30),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='abbrev',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('Core', 'core'), ('Custom', 'custom'), ('Suggested', 'suggested')], default='Custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.CharField(choices=[('other', 'other'), ('coa', 'COA'), ('spa', 'SPA')], default='spa', max_length=30, verbose_name='Funding Source'),
        ),
        migrations.AlterUniqueTogether(
            name='projectfunding',
            unique_together=set([('project', 'source')]),
        ),
    ]
