# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-09 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjtk2', '0019_auto_20180712_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='level',
            field=models.CharField(choices=[('actionrequired', 'Action Required'), ('info', 'Info')], default='info', max_length=30),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('Custom', 'custom'), ('Suggested', 'suggested'), ('Core', 'core')], default='Custom', max_length=30),
        ),
    ]
