# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-11 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pjtk2.models


class Migration(migrations.Migration):

    dependencies = [
        ('pjtk2', '0020_auto_20181009_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('picture', models.ImageField(upload_to=pjtk2.models.ProjectImage.get_image_path)),
                ('caption', models.CharField(blank=True, max_length=250, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pjtk2.Project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee'), ('dba', 'DBA')], db_index=True, default='Employee', max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('actionrequired', 'Action Required')], default='info', max_length=30),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('Custom', 'custom'), ('Core', 'core'), ('Suggested', 'suggested')], default='Custom', max_length=30),
        ),
    ]
