# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-11 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjtk2', '0021_auto_20181011_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='picture',
            new_name='image_path',
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('dba', 'DBA'), ('manager', 'Manager'), ('employee', 'Employee')], db_index=True, default='Employee', max_length=30),
        ),
    ]
