# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjtk2', '0022_auto_20181011_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='report',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('dba', 'DBA'), ('manager', 'Manager')], db_index=True, default='Employee', max_length=30),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('Core', 'core'), ('Suggested', 'suggested'), ('Custom', 'custom')], default='Custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(default='Fake Caption', max_length=1000),
            preserve_default=False,
        ),
    ]
