# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-13 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjtk2', '0023_auto_20181012_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('dba', 'DBA'), ('manager', 'Manager'), ('employee', 'Employee')], db_index=True, default='Employee', max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='level',
            field=models.CharField(choices=[('actionrequired', 'Action Required'), ('info', 'Info')], default='info', max_length=30),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('Custom', 'custom'), ('Core', 'core'), ('Suggested', 'suggested')], default='Custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(max_length=1000, verbose_name='figure caption'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='the order that the images are presented'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='report',
            field=models.BooleanField(default=True, verbose_name='should this image be included in the annual report too?'),
        ),
    ]
